# Paramétrage de l'environnement de travail et import des packages

In [2]:
import sys
from pathlib import Path

In [3]:
ROOT = Path.cwd().parents[0]

RAW_DATA = ROOT / "01_data" / "01_raw"
PROCESSED_DATA = ROOT / "01_data" / "02_processed"

%load_ext autoreload
%autoreload 2
sys.path.append(str(ROOT / "03_fonctions"))

In [4]:
import pandas as pd
from fonctions_perso.geo_localisation import calcul_distances
from cleaning.feature_engineering_and_selection import data_fraud_cleaning

# La base de données initiale

In [5]:
data_fraud_1 = pd.read_csv(RAW_DATA / "fraudTest.csv")
data_fraud_2 = pd.read_csv(RAW_DATA / "fraudTrain.csv")

In [6]:
data_fraud = pd.concat([data_fraud_1,data_fraud_2], axis=0)

**Informations globales**

In [7]:
data_fraud.info() # Pas de valeurs manquantes !

<class 'pandas.core.frame.DataFrame'>
Index: 1852394 entries, 0 to 1296674
Data columns (total 23 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Unnamed: 0             int64
 1   trans_date_trans_time  object
 2   cc_num                 int64
 3   merchant               object
 4   category               object
 5   amt                    float64
 6   first                  object
 7   last                   object
 8   gender                 object
 9   street                 object
 10  city                   object
 11  state                  object
 12  zip                    int64
 13  lat                    float64
 14  long                   float64
 15  city_pop               int64
 16  job                    object
 17  dob                    object
 18  trans_num              object
 19  unix_time              int64
 20  merch_lat              float64
 21  merch_long             float64
 22  is_fraud               int64
dtypes: float64(5), int64(6), object(12)
memory usage: 339.2+ MB

**Statistiques descriptives**

In [7]:
data_fraud.describe()

,Unnamed: 0,cc_num,amt,zip,lat,long,city_pop,unix_time,merch_lat,merch_long,is_fraud
count,1.852394e+06,1.852394e+06,1.852394e+06,1.852394e+06,1.852394e+06,1.852394e+06,1.852394e+06,1.852394e+06,1.852394e+06,1.852394e+06,1.852394e+06
mean,5.371934e+05,4.173860e+17,7.006357e+01,4.881326e+04,3.853931e+01,-9.022783e+01,8.864367e+04,1.358674e+09,3.853898e+01,-9.022794e+01,5.210015e-03
std,3.669110e+05,1.309115e+18,1.592540e+02,2.688185e+04,5.071470e+00,1.374789e+01,3.014876e+05,1.819508e+07,5.105604e+00,1.375969e+01,7.199217e-02
min,0.000000e+00,6.041621e+10,1.000000e+00,1.257000e+03,2.002710e+01,-1.656723e+02,2.300000e+01,1.325376e+09,1.902742e+01,-1.666716e+02,0.000000e+00
25%,2.315490e+05,1.800429e+14,9.640000e+00,2.623700e+04,3.466890e+01,-9.679800e+01,7.410000e+02,1.343017e+09,3.474012e+01,-9.689944e+01,0.000000e+00
50%,4.630980e+05,3.521417e+15,4.745000e+01,4.817400e+04,3.935430e+01,-8.747690e+01,2.443000e+03,1.357089e+09,3.936890e+01,-8.744069e+01,0.000000e+00
75%,8.335758e+05,4.642255e+15,8.310000e+01,7.204200e+04,4.194040e+01,-8.015800e+01,2.032800e+04,1.374581e+09,4.195626e+01,-8.024511e+01,0.000000e+00
max,1.296674e+06,4.992346e+18,2.894890e+04,9.992100e+04,6.669330e+01,-6.795030e+01,2.906700e+06,1.388534e+09,6.751027e+01,-6.695090e+01,1.000000e+00

**Aperçu rapide des données**

In [8]:
data_fraud.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0

# Base de données après transformations

In [8]:
data_fraud = data_fraud_cleaning()

Import des données et modification des types : OK
==================================================
Renommage des variables : OK
==================================================
Nettoyage de la variable 'nom_magasin' : OK
==================================================
Création des nouvelles variables : OK
==================================================
Suppressions des variables non utilisables : OK
==================================================
✅ Datasource 'data_fraud' prête.
📸 Asset 'cleaning_engineering_selection' mis à jour.

Calculating Metrics:   0%|          | 0/2 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/3 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/7 [00:00<?, ?it/s]

Règle 1 (expect_column_to_exist): OK
Règle 2 (expect_column_values_to_not_be_null): OK
Règle 3 (expect_table_column_count_to_equal): OK
Les conditions sont validés, export possible
Export des données : OK
==================================================

**Informations globales**

In [9]:
data_fraud.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1852394 entries, 0 to 1296674
Data columns (total 20 columns):
 #   Column                     Dtype
---  ------                     -----
 0   date_heure_transaction     datetime64[ns]
 1   nom_magasin                object
 2   type_magasin               object
 3   montant_transaction        float64
 4   ville_client               object
 5   etat_client                object
 6   latitude_domicile_client   float64
 7   longitude_domicile_client  float64
 8   population_ville_client    int64
 9   profession_client          object
 10  numero_transaction         object
 11  latitude_magasin           float64
 12  longitude_magasin          float64
 13  target                     int64
 14  annee_transaction          int32
 15  mois_transaction           object
 16  jour_transaction           object
 17  heure_transaction          int32
 18  distance_domicile_magasin  float64
 19  age_client                 int32
dtypes: datetime64[ns](1), float64(6), int32(3), int64(2), object(8)
memory usage: 275.6+ MB

**Statistiques descriptives**

In [10]:
data_fraud.describe()

,date_heure_transaction,montant_transaction,latitude_domicile_client,longitude_domicile_client,population_ville_client,latitude_magasin,longitude_magasin,target,annee_transaction,heure_transaction,distance_domicile_magasin,age_client
count,1852394,1.852394e+06,1.852394e+06,1.852394e+06,1.852394e+06,1.852394e+06,1.852394e+06,1.852394e+06,1.852394e+06,1.852394e+06,1.852394e+06,1.852394e+06
mean,2020-01-20 21:31:46.801825536,7.006357e+01,3.853931e+01,-9.022783e+01,8.864367e+04,3.853898e+01,-9.022794e+01,5.210015e-03,2.019501e+03,1.280612e+01,7.611183e+01,4.621138e+01
min,2019-01-01 00:00:18,1.000000e+00,2.002710e+01,-1.656723e+02,2.300000e+01,1.902742e+01,-1.666716e+02,0.000000e+00,2.019000e+03,0.000000e+00,2.225455e-02,1.400000e+01
25%,2019-07-23 04:13:43.750000128,9.640000e+00,3.466890e+01,-9.679800e+01,7.410000e+02,3.474012e+01,-9.689944e+01,0.000000e+00,2.019000e+03,7.000000e+00,5.532016e+01,3.300000e+01
50%,2020-01-02 01:15:31,4.745000e+01,3.935430e+01,-8.747690e+01,2.443000e+03,3.936890e+01,-8.744069e+01,0.000000e+00,2.020000e+03,1.400000e+01,7.821649e+01,4.400000e+01
75%,2020-07-23 12:11:25.249999872,8.310000e+01,4.194040e+01,-8.015800e+01,2.032800e+04,4.195626e+01,-8.024511e+01,0.000000e+00,2.020000e+03,1.900000e+01,9.850960e+01,5.700000e+01
max,2020-12-31 23:59:34,2.894890e+04,6.669330e+01,-6.795030e+01,2.906700e+06,6.751027e+01,-6.695090e+01,1.000000e+00,2.020000e+03,2.300000e+01,1.521174e+02,9.600000e+01
std,NaN,1.592540e+02,5.071470e+00,1.374789e+01,3.014876e+05,5.105604e+00,1.375969e+01,7.199217e-02,4.999996e-01,6.815753e+00,2.911701e+01,1.739545e+01

**Apercu rapide des données**

In [11]:
data_fraud.head()

,date_heure_transaction,nom_magasin,type_magasin,montant_transaction,ville_client,etat_client,latitude_domicile_client,longitude_domicile_client,population_ville_client,profession_client,numero_transaction,latitude_magasin,longitude_magasin,target,annee_transaction,mois_transaction,jour_transaction,heure_transaction,distance_domicile_magasin,age_client
0,2020-06-21 12:14:25,Kirlin and Sons,personal_care,2.86,Columbia,SC,33.9659,-80.9355,333497,Mechanical engineer,2da90c7d74bd46a0caf3777415b3ebd3,33.986391,-81.200714,0,2020,June,Sunday,12,24.561496,52
1,2020-06-21 12:14:33,Sporer-Keebler,personal_care,29.84,Altonah,UT,40.3207,-110.4360,302,"Sales professional, IT",324cc204407e99f51b0d6ca0055005e7,39.450498,-109.960431,0,2020,June,Sunday,12,104.925237,30
2,2020-06-21 12:14:53,"Swaniawski, Nitzsche and Welch",health_fitness,41.28,Bellmore,NY,40.6729,-73.5365,34496,"Librarian, public",c81755dbbbea9d5c77f094348a7579be,40.495810,-74.196111,0,2020,June,Sunday,12,59.080159,50
3,2020-06-21 12:15:15,Haley Group,misc_pos,60.05,Titusville,FL,28.5697,-80.8191,54767,Set designer,2159175b9efe66dc301f149d3d5abf8c,28.812398,-80.883061,0,2020,June,Sunday,12,27.698606,33
4,2020-06-21 12:15:17,Johnston-Casper,travel,3.19,Falmouth,MI,44.2529,-85.0170,1126,Furniture designer,57ff021bd3f328f8738bb535c302a31b,44.959148,-85.884734,0,2020,June,Sunday,12,104.335250,65

# Note explicative du Notebook

Ce notebook a pour objectif de préparer les données brutes avant les phases d’analyse exploratoire et de modélisation.  
Il regroupe l’import des données, le nettoyage, la création de variables ainsi que l’export d’une table prête à être utilisée.

---

## Import et fusion des données

Les fichiers `fraudTrain.csv` et `fraudTest.csv` sont chargés puis regroupés en une seule table.

Plusieurs opérations sont réalisées lors de cette étape :
- conversion des types de variables (dates en datetime, identifiants en object)
- suppression de la colonne technique `Unnamed: 0`
- concaténation des deux jeux de données

Ce regroupement permet de garder la main sur le découpage train, validation et test, en particulier dans une logique temporelle cohérente avec le cas d’usage.

---

## Renommage des variables

Les colonnes sont renommées avec des intitulés plus explicites et orientés métier.

Par exemple :
- `amt` devient `montant_transaction`
- `trans_date_trans_time` devient `date_heure_transaction`
- `is_fraud` devient `target`

L’objectif est d’améliorer la lisibilité du dataset et de faciliter l’interprétation des résultats par la suite.

---

## Nettoyage ciblé

Un nettoyage est appliqué sur certaines variables catégorielles, notamment `nom_magasin`, afin de supprimer des préfixes techniques inutiles.

Cela permet d’éviter une multiplication artificielle des modalités et de garder une représentation plus propre des données.

---

## Création de variables

Plusieurs variables sont construites à partir des données existantes afin d’enrichir l’information disponible pour la modélisation.

### Variables temporelles

À partir de `date_heure_transaction`, les variables suivantes sont créées :
- `mois_transaction`
- `jour_transaction`
- `heure_transaction`

Elles permettent de capturer des effets liés au moment de la transaction.

### Variable géographique

- `distance_domicile_magasin`

Elle est calculée à partir des coordonnées du client et du commerçant, puis exprimée en kilomètres.  
Les coordonnées brutes ne sont pas conservées, la distance étant plus directement exploitable.

### Variable démographique

- `age_client`

Elle est calculée à partir de la date de transaction et de la date de naissance.

---

## Suppression de variables

Certaines variables sont supprimées car non exploitables, redondantes ou non pertinentes dans le cadre du modèle :

- identifiants uniques (`numero_carte`, `trans_num`)
- informations personnelles (`prenom`, `nom`, adresse complète)
- variable sensible (`sexe`)
- variables redondantes (`timestamp_unix_transaction`, coordonnées brutes)
- variables remplacées par des variables dérivées (`date_heure_transaction`, `date_naissance_client`)

Cette étape permet de réduire le bruit, de simplifier le dataset et de limiter les risques de fuite d’information.

---

## Contrôle qualité

Un contrôle est réalisé avec Great Expectations afin de vérifier la cohérence des données :

- présence de la variable cible `target`
- absence de valeurs manquantes sur cette variable
- conformité du nombre de colonnes

L’export n’est effectué que si ces conditions sont respectées.

---

## Export

La table finale, nettoyée et enrichie, est exportée au format parquet.  
Elle servira de base pour le notebook suivant consacré à l’analyse exploratoire des données.